version: '3.8'
services:
 

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    networks:
      - my-network
    restart: always

networks:
  my-network:
    name: hub
    driver: bridge

volumes:
  db_data:

